export const REQUEST_TODO = 'REQUEST_TODO';
export const REQUEST_TODOS = 'REQUEST_TODOS';
export const RECEIVE_TODOS = 'RECEIVE_TODOS';
export const RECEIVE_TODO = 'RECEIVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const CONFIRM_DELETE_TODO = 'CONFIRM_DELETE_TODO';
export const CHANGE_EDITMODE = 'CHANGE_EDITMODE';
export const REQUEST_UPDATE = 'REQUEST_UPDATE';
export const CONFIRM_UPDATE = 'CONFIRM_UPDATE';

export const ADD_TODO = 'ADD_TODO';
export const GET_TODOS = 'GET_TODOS';
